#os: linux
#arch: s390x
#language: ruby
#rvm:
# - 2.7
#
#before_install:
# - sudo apt-get update -q
# - sudo apt-get install postgresql-12
# - sudo apt-get install shared-mime-types
# - sudo gem install bundler
# - sudo bundle config build.pg && bundle install --deployment --path vendor/bundle


language: ruby
sudo: false
dist: bionic
arch:
- ppc64le
- s390x
services:
  - postgresql
